### ISSUE TITLE
promblem about downloading this dataset

### ISSUE THREAD

**Issue by LSun0717** [cabani/MaskedFace-Net#12]
I can't download this dataset，what should i do for solving this problem and hope you can give me some suggestions.
thank you!

**Comment by cabani** [comment]
Hello @LSun0717,
You could use these links:

67,049 images with Correctly Masked Face Dataset (CMFD) at 1024×1024: [Go to OneDrive (19 GB)](https://esigelec-my.sharepoint.com/:f:/g/personal/cabani_esigelec_fr/Ev3GdnQSyzxPjyzU5ElHqagBlkRCaKnnCI85iX-d1L4OHA?e=G7uaYV)

66,734 images with Incorrectly Masked Face Dataset (IMFD) at 1024×1024: [Go to OneDrive (19 GB)](https://esigelec-my.sharepoint.com/:f:/g/personal/cabani_esigelec_fr/EirjS8ew7-5LnO8I56Uk63wBKebwSlukFBFBaO8N25wn3g?e=Ho1jHG)

or the following mirror links:
Zip file CMFD: [Part 1](https://drive.google.com/file/d/17-FCstm8Fz3bDzFgTmOWHa_c39lTR_1P/view?usp=sharing) - [Part 2](https://drive.google.com/file/d/1XClQlP9_V6UmmnwTyzjF28vlrVHNSw2H/view?usp=sharing)

Zip file IMFD: [Part 1](https://drive.google.com/file/d/1gjltyD_MnNWcnd56NnjUOizdi39CUEPF/view?usp=sharing) - [Part 2](https://drive.google.com/file/d/1qvbcuTHSLBTxQd3wXNAUIYVXBBJCa2WF/view?usp=sharing)
Best regards

**Comment by cabani** [comment]
Dear @LSun0717,
The MaskedFace-Net is based on on the dataset Flickr-Faces-HQ (FFHQ). So you can dowload directly the raw dataset in the following link: [dataset Flickr-Faces-HQ (FFHQ)](https://github.com/NVlabs/ffhq-dataset).
Best regards
