### ISSUE TITLE
Generating masked faces

### ISSUE THREAD

**Issue by drajsel** [cabani/MaskedFace-Net#2]
Hello @cabani, 

will you be releasing your implementation of the algorithm for generating masked faces at some point? 

Best regards,
Dorotea

**Comment by cabani** [comment]
Hello Dorotea (@drajsel),

Stages and libs of our implementation for generating masked faces are described in the data paper. The algorithm mixes some pieces of code under review and is not available at the moment.

Best regards
MaskedFace-Net team

**Comment by drajsel** [comment]
I read the paper, but I was interested in some details. Nevertheless, thank you for answering, @cabani.

Best,
Dorotea
