### ISSUE TITLE
Masked face generation using algorithm

### ISSUE THREAD

**Issue by anirudhagar13** [cabani/MaskedFace-Net#3]
Hi, we need to generate this data with different types of masks for a class project we are working on. Would it be possible for you to provide the algorithm code? Thanks.

**Comment by cabani** [comment]
Hello Anirudh Agarwal (@anirudhagar13) ,

Our algorithm mixes some pieces of code under review and is not available at the moment. However, methodology and libs permitting to generate data with other types of masks are described in the data paper.

Best regards,
MaskedFace-Net team

**Comment by dhyanid13** [comment]
Hi , I want to develop a neural network algorithm to detect the masked face in my python code.Can i get a csv file of this dataset of images in the pixel format of RGB?

**Comment by cabani** [comment]
Hello @dhyanid13,

Please can you clarify your question. 
What do you mean by "dataset of images in the pixel format of RGB"?
What exactly do you expect?

Best regards,
MaskedFace-Net team

**Comment by dhyanid13** [comment]
Thanks @cabani  for the reply.
Actually what I am trying to say was trying to say was something else about the  dataset  but now the problem is sorted.
