### ISSUE TITLE
Problem downloading, hosting the data elsewhere

### ISSUE THREAD

**Issue by vladoski** [cabani/MaskedFace-Net#4]
Greetings, I'm trying to download this dataset, yet I have some problems downloading it.  
I've tried to download the entire dataset from sharepoint but everytimes the download breaks and stops. I've tried to download some subdirectories separately without success (every now and then the download stops or inside the zip that I've downloaded there's full of txts explaining the errors).  

Could you please host the dataset elsewhere?
Also thanks for your work!

**Comment by cabani** [comment]
Hello @vladoski ,

We suggest you to use a download manager tool or OneDrive sync client.

Best regards
MaskedFace-Net team
