### ISSUE TITLE
Error.txt downloading. Hosting elsewhere?

### ISSUE THREAD

**Issue by gongarher** [cabani/MaskedFace-Net#5]
Hi, I have been trying to download this dataset but it's being a nightmare. I have tried with different browsers like chrome, edge, and internet explorer, and it always ends up crashing into a corrupt file. I have also tried with onedrive sync client without success. I think it's because of the size (20Gb). I have also read #4 Could you please host elsewhere apart from  OneDrive/SharePoint? That will give access to everyone. There are no available options left in order to download it correctly from SharePoint. Moreover, download speed isn't too fast on SharePoint.

Thanks for the support!

**Comment by cabani** [comment]
Hello @gongarher,
 
To facilitate the downloading of our dataset, we suggest you to use a download manager tool (like DownThemAll! – Addons for firefoxhttps://addons.mozilla.org/fr/firefox/addon/downthemall/) or OneDrive sync client.

Best regards,
MaskedFace-Net team

**Comment by gongarher** [comment]
Thanks for your quick support. Have you tried to download images using a download manager tool? Because of the SharePoint web structure, it's impossible for me with DwonThemAll! I have also tried to download it through OneDrive sync client without success. Thanks for your help but I'm still stuck downloading your great dataset.

**Comment by gongarher** [comment]
Finally I have downloaded folder by folder. It has been the best way for me. Thanks!
